<a href="https://colab.research.google.com/github/AmitUdugade/DataScience/blob/main/Machine%20Learning/ML03_Joblib_and_Pickle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

df = pd.read_csv('Downloads/Datasets - ML/homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [ ]:
df.head(3)

area   price
0  2600  550000
1  3000  565000
2  3200  610000

In [ ]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression()

In [ ]:
model.coef_

array([135.78767123])

In [ ]:
model.intercept_

180616.43835616432

In [ ]:
import pickle

In [ ]:
with open('model_pickle','wb') as file:
    pickle.dump(model, file)

In [ ]:
with open('model_pickle','rb') as f:
          mp = pickle.load(f)

In [ ]:
mp.coef_

array([135.78767123])

In [ ]:
mp.intercept_

180616.43835616432

In [ ]:
mp.predict([[5000]])

C:\Users\imami\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [ ]:
import joblib

In [ ]:
joblib.dump(model, 'model_joblib')

mj = joblib.load('model_joblib')

mj.coef_


array([135.78767123])

In [ ]:
mj.intercept_

180616.43835616432

In [ ]:
mj.predict([[5000]])

C:\Users\imami\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])